### ISSUE TITLE
/giphy command stops appearing after some time

### ISSUE THREAD

**Issue by maurice-schleussinger** [wreiske/Rocket.Chat.App-Giphy#12]
**Affected clients:** all browsers and desktop clients
**Rocketchat version (server):** 2.4.1

Hi! 👋

For our instance the /giphy command simply stops appearing for the users after some time.
The app is active and does start though. We tried reinstalling it, to no effect.

**Log of the app:**

Any idea what could affect this?

`debug: 2020-01-29T12:44:32.917Z (Caller: anonymous OR constructor)
[
  "onSettingUpdated is being called..."
]
debug: 2020-01-29T12:44:32.920Z (Caller: anonymous OR constructor)
[
  "'onSettingUpdated' was successfully called! The result is:",
  null
]`

Thanks for creating this app and for any pointers! 👍

**Comment by wreiske** [comment]
This sounds more like a Rocket.Chat issue than something in the app code. Do you mind opening an issue on https://github.com/RocketChat/Rocket.Chat/issues and linking to this issue?

I will also poke Rocket.Chat support once you've created the issue there. 

Thanks!

**Comment by maurice-schleussinger** [comment]
@wreiske Did you have a chance to look into this yet? 🙂

**Comment by wreiske** [comment]
It's definitely a Rocket.Chat issue and not anything wrong with the code on this repo. I'm going to keep this open, however, since the Giphy app is affected by it.

**Comment by robinreinhardt** [comment]
You are right! We also had an Android and iOS App login issue

After changing following value in the admin seetings the Giphy App still works again.

In the settings under General -> REST API an incorrect value was set at Default Count
After I set the value from 1 to 50 (default value) the giphy app works again and keep working.

Also see: https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2006
