### ISSUE TITLE
Gifs should only play on hover

### ISSUE THREAD

**Issue by MondaySam** [wreiske/Rocket.Chat.App-Giphy#18]
Hey.
I don't know if this project is still supported, but I would suggest an option or a default so that gifs don't loop endlessly as this becomes really annoying really fast.

I would suggest a play on hover - and optionally a short automatic loop interval (e.g. 3-5 loops) and then back to "play on hover".

**Comment by wreiske** [comment]
@MondaySam hello! Sorry it's taken almost an entire year for a response... This is more of a Rocket.Chat Apps Engine change. You can submit a feature request here: https://github.com/RocketChat/feature-requests
