### ISSUE TITLE
Cannot install App (Manual upload)

### ISSUE THREAD

**Issue by kr3t3n** [wreiske/Rocket.Chat.App-Giphy#19]
I have Development mode enabled and I am trying to install the app from the source code download but I get the following error in RC:

Invalid App package. Could not find the classFile (Tenor.js) file.

**Comment by crossRT** [comment]
same problem.
any solution for this problem?

**Comment by wreiske** [comment]
There may have been a change to the APIs for Rocket.Chat. Have you tried changing the apps engine version?

**Comment by ankar84** [comment]
> Invalid App package. Could not find the classFile (Tenor.js) file.

Same here.
Is there way to install apps manually?

**Comment by yash-rajpal** [comment]
@wreiske @ankar84 I have created a PR #22 updating the deps and making required changes for newer versions of RocketChat and Apps Engine, please have a look.

Thanks!

**Comment by wreiske** [comment]
Thank you! I will take a look.

**Comment by wreiske** [comment]
Resolved by #22!

I'll see if I can get these pushed out to the Rocket.Chat Marketplace.
