### ISSUE TITLE
Broken after RocketChat 4.4.0 upgrade (from 4.3.3)

### ISSUE THREAD

**Issue by ThomasBuchinger** [wreiske/Rocket.Chat.App-Giphy#25]
Giphy Plugin stopped working after the Upgrade from RocketChat 3.18.0, with Giphy-Plugin (I believe it was 0.0.4 but I am not 100% sure) to RocketChat 4.4. 

When I type `/giphy`, I get a Preview-Windows, which just says "Loading" and nothing happens. And in RocketChat log, I get the following message. Any Idea how to debug this?

```
{"level":50,"time":"2022-02-01T12:31:30.760Z","pid":1,"hostname":"rocketchat-rocketchat-8447f67c5f-85wbz","name":"","name":"System","msg":"Exception while invoking method getSlashCommandPreviews 'Cannot read property 'id' of undefined'"}
```

So far I've tried:
* Uninstall App and Reinstall it again
* Change Giphy API Keys (tried both SDK and API Type), both keys are rate-limited beta-keys

Current Configuration:
* Giphy Plugin 0.0.6 (Marketplace)
* RocketChat 4.4.0
* MongoDB 5.0

Last known Working Configuration:
* Giphy Plugin 0.0.4 (Marketplace)
* RocketChat 3.18.0
* MongoDB 4.2

Edit: It seems to be a RocketChat Bug. It used to work in 4.3.3

**Comment by Bugt** [comment]
Can confirm, just updated to 

- RocketChat 4.4.0

same issue.

**Comment by ThomasBuchinger** [comment]
@Bugt Did it work pre-4.4.0? I did the upgrade from 3.18.0 to 4.4.0 directly and can't easily go back to test if 4.3 would have worked

**Comment by 3x3cut0r** [comment]
for me it worked till 4.3.x. 
with 4.4.0 it has broken too.

so last known working configuration:

Giphy Plugin 0.0.6 (Marketplace)
RocketChat 4.3.x
MongoDB 5.x

**Comment by Bugt** [comment]
Yes it did work pre-4.4.0 so my last working configuration was:

- Giphy Plugin 0.0.6 (Marketplace)
- RocketChat 4.0.x
- MongoDB 4.2

(I updated from 4.0.x to 4.4.0)

**Comment by wreiske** [comment]
I'll send this issue over to the RC team. Maybe something broke in apps engine. Thanks for the report.

**Comment by RomanSixty** [comment]
All three apps (Imgur, Giphy and Tenor) seem to be affected. I get error messages in my logs, e.g.:

```
Exception while invoking method 'getSlashCommandPreviews' TypeError: Cannot read property 'id' of undefined
    at Object._executeSlashCommandPreview [as getPreviews] (app/utils/lib/slashCommand.js:34:17)
    at MethodInvocation.getSlashCommandPreviews (app/lib/server/methods/getSlashCommandPreviews.js:26:24)
    at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:74:34)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1885:12)
    at packages/ddp-server/livedata_server.js:769:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
    at packages/ddp-server/livedata_server.js:767:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
    at packages/ddp-server/livedata_server.js:765:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:739:23)
    at packages/ddp-server/livedata_server.js:603:43
```

**Comment by wreiske** [comment]
Looks like something related to previews did break in RC since possibly 4.3. I asked for the RC team to please reply here with any info they have and if a fix is coming.

**Comment by Crashdummyy** [comment]
Log of npm ci:
```
9 verbose lifecycle tiny-secp256k1@1.1.3~build: CWD: /tmp/bundle/programs/server/npm/node_modules/tiny-secp256k1
10 silly lifecycle tiny-secp256k1@1.1.3~build: Args: [ '-c', 'node-gyp rebuild' ]
11 silly lifecycle tiny-secp256k1@1.1.3~build: Returned: code: 1  signal: null
12 info lifecycle tiny-secp256k1@1.1.3~build: Failed to exec build script
13 verbose stack Error: tiny-secp256k1@1.1.3 build: `node-gyp rebuild`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
14 verbose pkgid tiny-secp256k1@1.1.3
15 verbose cwd /tmp/bundle/programs/server/npm/node_modules/tiny-secp256k1
16 verbose Linux 4.19.0-18-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v14.18.3
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error tiny-secp256k1@1.1.3 build: `node-gyp rebuild`
22 error Exit status 1
23 error Failed at the tiny-secp256k1@1.1.3 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Could this have something to do with this ?

**Comment by ThomasBuchinger** [comment]
If anyone is stuck on 4.4.0 and cannot wait for an upstream fix, I managed to downgrade RocketChat by manually setting the DB migration version and starting the 4.3.3 container. Obviously this is not supported, I haven't checked what this specific migration actually contains

```
# Stop RocketChat and connect to MongoDB
use rocketchat
db.migrations.update({"version":253},{"version":252})
``` 
This sets the "database-version" to the version used by 4.3.3, but it does not actually change the database, so the RocketChat-code is now slightly incompatible with the database. This lets RocketChat 4.3.3 start.
Once the fix is available, you can change it back to the correct version and update RocketChat from there

**Comment by dudanogueira** [comment]
Hi!

We have upgraded meteor in 4.4.0 and are experiencing some unexpected behaviors.

Team is already onto it. Thanks!!

**Comment by Crashdummyy** [comment]
> If anyone is stuck on 4.4.0 and cannot wait for an upstream fix, I managed to downgrade RocketChat by manually setting the DB migration version and starting the 4.3.3 container. Obviously this is not supported, I haven't checked what this specific migration actually contains
> 
> ```
> # Stop RocketChat and connect to MongoDB
> use rocketchat
> db.migrations.update({"version":253},{"version":252})
> ```
> 
> This sets the "database-version" to the version used by 4.3.3, but it does not actually change the database, so the RocketChat-code is now slightly incompatible with the database. This lets RocketChat 4.3.3 start. Once the fix is available, you can change it back to the correct version and update RocketChat from there

While its generally a bad idea to mess with the dbVersion it wont hurt here.
[Migration252](https://github.com/RocketChat/Rocket.Chat/blob/7632f12cfcc7ed8ee8f843587fdff63b101cc765/server/startup/migrations/v252.ts) should be able to run more than once

**Comment by 3x3cut0r** [comment]
Downgrading to 4.3.3 with the mongo db.migrations.update works perfectly with my docker instance. giphy is back and some client connection issues are gone!

some news on this here?

**Comment by Crashdummyy** [comment]
> Downgrading to 4.3.3 with the mongo db.migrations.update works perfectly with my docker instance. giphy is back and some client connection issues are gone!
> 
> some news on this here?

The fix is already merged.
We just have to wait for 4.4.1

**Comment by ThomasBuchinger** [comment]
Rocketchat 4.4.1 is released. Plugin Works again.
Thanks for the Help
