### ISSUE TITLE
remove static date from title

### ISSUE THREAD

**Issue by bigcammy** [wreiske/Rocket.Chat.App-Giphy#3]
Is there any way to keep the static date of "December 31, 1969 6:00PM" from showing on every giphy?

**Comment by wreiske** [comment]
> Is there any way to keep the static date of "December 31, 1969 6:00PM" from showing on every giphy?

I submitted a pull-request to rocket.chat's official repository and it will be in the next release. 
https://github.com/RocketChat/Rocket.Chat/pull/13428
