### ISSUE TITLE
Date problem

### ISSUE THREAD

**Issue by iooner** [wreiske/Rocket.Chat.App-Giphy#5]
<img width="249" alt="Capture d’écran 2019-04-01 à 21 27 48" src="https://user-images.githubusercontent.com/3057138/55354067-10e14500-54c5-11e9-9fd9-7169633d2eae.png">
Date stuck in 01/01/1970

**Comment by wreiske** [comment]
Related to #3 

Waiting on the next Rocket.Chat release. I fixed this in https://github.com/RocketChat/Rocket.Chat/pull/13428
