### ISSUE TITLE
Mobile Support

### ISSUE THREAD

**Issue by CodyPChristian** [wreiske/Rocket.Chat.App-Giphy#6]
Hello, will there be any support for this within the mobile apps? So far it doesn't pop up the preview pane when using the mobile app.

**Comment by wreiske** [comment]
That's completely up to the Rocket.Chat team / the community to implement into the mobile apps. Once the mobile apps support it, I will make sure Giphy supports it too.

Maybe @rafaelks can provide some input?

**Comment by rafaelks** [comment]
@wreiske We would love to do it, but first we need to have few definitions on how this kind of apps should work on the mobile apps, and we don't have it yet. Thanks!

**Comment by wreiske** [comment]
I've added a "help wanted" label to this. If anyone is coming here wanted to help implement this, you would need to submit pull requests to both:
https://github.com/RocketChat/Rocket.Chat.IOS
https://github.com/RocketChat/Rocket.Chat.Android

**Comment by lbblitz54** [comment]
i was so close to deploying to a few thousand of our users... and this is whats going to kill it for them lol
hope yall get the giphs working, i guess we're moving to Matrix

**Comment by wreiske** [comment]
@lbblitz54 this works now on the mobile experimental apps. The mobile apps are moving to experimental very soon, too, so all your users would have it in mobile.

**Comment by lbblitz54** [comment]
Any expected drop date or just "soonTM" @wreiske 
lord knows that the people will revolt without their memes so this is great news.
