### ISSUE TITLE
[BUG]: can't upload image because of bad url

### ISSUE THREAD

**Issue by Venomen** [wreiske/Rocket.Chat.App-Giphy#7]
In new Rocketchat server version (1.0.0-rc.2) there is "/" added to the beginning of url, making pasted image impossible to watch. Doesn't matter if application or web version:

![rocket-giphy-bug](https://user-images.githubusercontent.com/3985913/56313295-936b3500-6152-11e9-8d3a-01aea880ed6d.gif)

**Comment by wreiske** [comment]
This has been resolved and we're waiting for Rocket.Chat to release the next RC. We had this same issue with or Tenor app, https://github.com/wreiske/Rocket.Chat.App-Tenor/issues/3 and I submitted a request for them to fix it.

https://github.com/RocketChat/Rocket.Chat/pull/14086

Thanks for the report.
