### ISSUE TITLE
Posts into threads do not appear in the thread

### ISSUE THREAD

**Issue by cryptobanana** [wreiske/Rocket.Chat.App-Giphy#9]
When a `/giphy` command is invoked in a thread (new feature in rocketchat 1.0.3) the resulting post does not go into the thread but into the parent channel.

![image](https://user-images.githubusercontent.com/1322972/57776442-cbe53b00-771f-11e9-9e8c-76d437d051fe.png)

**Comment by wreiske** [comment]
Thanks for the report. I think this is more of a Rocket.Chat apps engine issue... I'll get back to you when I know more.

**Comment by wreiske** [comment]
This is in fact an issue with the rocket.chat apps-engine. The developers are aware and will have a fix in "hopefully only a few weeks".

Thanks!

**Comment by wreiske** [comment]
This is now available in 0.0.5 update.
https://github.com/wreiske/Rocket.Chat.App-Giphy/commit/82cd8dc79653db3903281df09b7fd0e3970957dc
